language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
    - output

before_install:
  - npm -g install bower

install:
  - npm install
  - bower update
  - npm run build